### ISSUE TITLE
On interaction (specifically "no") throws an error: "ValueError("non-integer arg 1 for randrange()")"

### ISSUE THREAD

**Issue by IndianVersion** [Eggciting/canunot#1]
Error Message:

```txt
Traceback (most recent call last):
  File "/home/phantom/canunot/gen.py", line 23, in <module>
    gen()
  File "/home/phantom/canunot/gen.py", line 16, in gen
    sec_gen = random.randrange(num/2, 3000)
  File "/usr/lib/python3.9/random.py", line 303, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()
```

Elicits due to ``"num"`` variable becoming a "non-integer" on generating the random integer.

**Comment by IndianVersion** [comment]
Error tossing upon non-integer generation is now disambiguate/occur, now returns a "Retry Message"
